### PR TITLE
Modified incert to use nautls library

### PR DESCRIPTION
**Pull request by izzy-shirron**

### CODE REVIEW

**Comment by izzy-shirron** [comment]
@joshua-rutherford Sorry I had to fix the go mod on my computer so that it could build. The reason it isn't building is because of the EncodeCertificate function that was used before on root, intermediate, and leaf. Is it possible to get a variable from the Identity struct to pass into EncodeCertificate?

**Comment by izzy-shirron** [comment]
Or would the certificate function for Template work? It returns a certificate but I'm not sure if it would be encoded.

**Comment by joshua-rutherford** [comment]
The go.mod and go.sum files are checked into the repo (best practice: https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file).  So if you needed to modify to build you should check them in and add to the pull request.

**Comment by joshua-rutherford** [comment]
The lack of access to the authority certificates, identity certificate and identity key on a NauTLS `identity.Identity` and the fact that we don't expose encoding methods is a bit problematic I agree.

There are three ways we could handle this in my mind (all of which will require changes to NauTLS):

1. We can make those fields on the `Identity` struct public.
2. We can provide accessor functions for them.  Note that we have to deep copy using something like https://godoc.org/github.com/mitchellh/copystructure as simply returning the field values has the same effect as making those fields public since they are pointers or arrays of pointers:
> func (i *Identity) Authorities() []*x509.Certificate {
>     return copystructure.Must(i.authorities) 
> }
3. Add the encoding methods.
> func (i *Identity) PEMEncodeAuthorities() (string, error) {...}
>
> func (i *Identity) PEMEncodeCertificate() (string, error) {...}
>
> func (i *Identity) PEMEncodeKey() (string, error) {...}

I think I'd prefer the latter here because I'm not inclined to open up the struct as the three fields have to be atomic (i.e., they cannot be changed independently or the structure is invalid) and exposing them suggests that they can be manipulated.

**Comment by joshua-rutherford** [comment]
One last alternative is to add static functions in the `identities` package that encodes as they have access to the private fields.  So in `identities/encoding.go` create the following:
> ```
> func PEMEncodeAuthorities(identity *Identity) (string, error) {...}
>
> func PEMEncodeCertificate(identity *Identity) (string, error) {...}
>
> func PEMEncodeKey(identity *Identity) (string, error) {...}
> ```

**Comment by joshua-rutherford** [comment]
So pick from 3 or 4 above, open an issue in NauTLS and implement them.

**Comment by joshua-rutherford** [comment]
And for clarity, 3 and 4 probably get compiled to the exact same thing under the hood as the `func (a *A) Method()` syntax is likely just syntactic sugar for `func Method(a *A)`.

**Comment by joshua-rutherford** [comment]
I've opened https://github.com/DecipherNow/nautls/issues/16 in nautls to address this.

**Comment by joshua-rutherford** [comment]
closing until we can revisit more fully.

**Pull request closed without merging**
